#!/usr/bin/env bash

set -ex

export INTERFACE="vnet0"
export VNET="on"
export ROUTER="192.168.1.1"
export BOOT="on"

RELEASE=$(freebsd-version | sed "s/STABLE/RELEASE/g") && \
	export RELEASE

JAIL_NAME=$(basename "$(cd "$(dirname "$0")" || exit; pwd -P)") && \
	export JAIL_NAME

SETTINGS_PATH=/mnt/tank/apps/"$JAIL_NAME" && \
	export SETTINGS_PATH

ABS_DIR=$(cd "$(dirname "$0")" || exit; pwd -P) && \
	export ABS_DIR

PKG_JSON=$(mktemp "/tmp/$JAIL_NAME.XXX") && \
	export PKG_JSON

trap 'rm -f "$PKG_JSON" || true' EXIT

github_release() {
	local release="${3-latest}"

	wget -qO - "https://api.github.com/repos/$1/$2/releases/$release" \
		| grep "download_url.*" \
		| cut -d : -f 2,3 \
		| tr -d \" \
		| awk "/freebsd/ || /linux/" \
		| head -n 1
}
