#!/usr/bin/env bash

YDL=/usr/local/bin/youtube-dl

ARG1="${1?}"

ARG2="${2?youtube}"

ARG3="%(title)s.%(ext)s"

if [[ $ARG1 =~ (play)?list ]]
then
	ARG3="%(playlist)s/%(playlist_index)s - $ARG3"
fi

declare -a ARGS=(
	--continue
	--ignore-config
	--embed-thumbnail
	--no-check-certificate
	--add-metadata
	--retries infinite
	--merge-output-format mp4
	--format "bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio"
	--output "/mnt/media/$ARG2/%(uploader)s/$ARG3"
)

LC_ALL=en_US.UTF-8 "$YDL" "${ARGS[@]}" "$ARG1"
