#!/usr/bin/env bash

YDL=/usr/local/bin/youtube-dl

ARG1=${1?}
ARG2=${1?}

declare -a ARGS=(
	--ignore-config
	--embed-thumbnail
	--no-check-certificate
	--add-metadata
	--merge-output-format mp4
	--format "bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio"
	--output "/mnt/media/$ARG2/%(uploader)s/%(title)s.%(ext)s"
)

LC_ALL=en_US.UTF-8 "$YDL" "${ARGS[@]}" "$ARG1"
