#!/usr/bin/env bash

set -e

API=privateinternetaccess.com/vpninfo/port_forward_assignment &&
	export API

while ! nc -z 127.0.0.1 9091 </dev/null; do sleep 1; done

A12N=$(awk '$1 == "auth-user-pass" { while(( getline line < $2 ) > 0) { print line }}' /settings/vpn/default.ovpn)

declare -A params=(
	[user]=$(echo "$A12N" | head -n 1)
	[pass]=$(echo "$A12N" | sed -n 2p)
	[client_id]=$(head -n 100 /dev/urandom | md5 -r | tr -d ' -')
	[local_ip]=$(ifconfig tun0 | grep 'inet ' | cut -d\  -f2 | tee /tmp/vpn_ip)
)

JSON=$(wget -q --post-data="$(for key in "${!params[@]}"; do echo -n "$key=${params[${key}]}&"; done)" -O - $API)

transmission-remote 127.0.0.1 -p "$(echo $JSON | jq .port)"
