#!/usr/bin/env bash

set -x

JAIL_IP=192.168.1.10 && \
	export JAIL_IP

# shellcheck source=/dev/null
. jails/base

ABS_DIR=$(cd "$(dirname "$0")" || exit; pwd -P)

if [[ -f "$ABS_DIR"/vpn/default.ovpn && -f "$ABS_DIR"/vpn/default.auth ]]; then
	echo "you need to provide the openvpn's configuration and authentication files."
	exit 0
fi

devfs rule -s 4 add path 'tun*' unhide

zfs create tank/apps/"$JAIL_NAME"

cat <<EOF >/tmp/pkglist.json
{
	"pkgs": [
		"bash",
		"wget",
		"jq",
		"transmission-web",
		"transmission-daemon",
		"transmission-cli",
		"openvpn",
		"python36"
	]
}
EOF

iocage create -r "$RELEASE" -n "$JAIL_NAME" -p /tmp/pkglist.json \
	vnet="$VNET" \
	boot="$BOOT" \
	defaultrouter="$ROUTER" \
	ip4_addr="$INTERFACE|$JAIL_IP/24" \
	allow_raw_sockets="1" \
	allow_tun="1"

rm -f /tmp/pkglist.json

SETTINGS_PATH=/mnt/tank/apps/"$JAIL_NAME"

iocage exec "$JAIL_NAME" env ASSUME_ALWAYS_YES=YES \
	python3.6 -Im ensurepip --upgrade --default-pip

iocage exec "$JAIL_NAME" pw groupadd -g "$(id -g media)" -n media
iocage exec "$JAIL_NAME" pw groupmod media -m transmission
iocage exec "$JAIL_NAME" mkdir -p /settings /mnt/media/{movies,music,series}

iocage fstab -a "$JAIL_NAME" "$SETTINGS_PATH" /settings nullfs rw 0 0

# shellcheck disable=SC2016
find /mnt/tank/media/* -type d -maxdepth 0 -print0 \
	| xargs -0 -I@ bash -c "iocage fstab -a $JAIL_NAME @ /mnt/media/"'"$(basename @)"'" nullfs rw 0 0"

iocage exec "$JAIL_NAME" mkdir /settings/{ipfw,vpn,transmission}

VPN_DIR="$SETTINGS_PATH"/vpn && \
	export VPN_DIR

cp "$ABS_DIR"/vpn/forward_port "$VPN_DIR" && \
	cat <<-EOF >"$VPN_DIR"/up
		#!/usr/bin/env bash
		nohup bash /settings/vpn/forward_port &
	EOF

awk '{ printf "%s\n", $0 } END { print "script-security 2" "\n" "up /settings/vpn/up" }' \
	< "$ABS_DIR"/vpn/default.ovpn \
	> "$VPN_DIR"/default.ovpn

VPN_IP=$(awk '$1 == "remote" {print $2}' < "$VPN_DIR"/default.ovpn) 

VPN_AUTH=$(awk '$1 == "auth-user-pass" {print $2}' < "$VPN_DIR"/default.ovpn) && \
	export VPN_AUTH

cp "$ABS_DIR"/vpn/"$VPN_AUTH" "$VPN_DIR"/"$(basename "$VPN_AUTH")"

awk '/auth-user-pass/{$NF="'"/settings/vpn/$(basename "$VPN_AUTH")"'"} 1' \
	< "$VPN_DIR"/default.ovpn \
	> /tmp/ovpn.new \
		&& mv /tmp/ovpn.new "$VPN_DIR"/default.ovpn

IPFW_DIR="$SETTINGS_PATH"/ipfw

sed "s/JAIL_IP/$JAIL_IP/g; s/VPN_IP/$VPN_IP/g" < "$ABS_DIR"/ipfw/rules > "$IPFW_DIR"/rules

jq . < "$ABS_DIR"/transmission/settings.json > "$SETTINGS_PATH"/transmission/settings.json

cat <<-EOF | xargs -L1 iocage exec "$JAIL_NAME" > /dev/null 2>&1
	chgrp -R media /settings /mnt/media
	chown 0:0 /settings/ipfw/rules
	chmod 600 /settings/ipfw/rules
	chmod +x /settings/vpn/up
	chmod +x /settings/vpn/forward_port
	sysrc firewall_enable=YES
	sysrc firewall_type=/settings/ipfw/rules
	sysrc openvpn_enable=YES
	sysrc openvpn_dir=/settings/vpn
	sysrc openvpn_configfile=/settings/vpn/default.ovpn
	sysrc transmission_enable=YES
	sysrc transmission_user=transmission
	sysrc transmission_conf_dir=/settings/transmission
	sysrc transmission_download_dir=/mnt/media
	service ipfw start
	service openvpn start
	service transmission start
EOF
