#!/usr/bin/env bash

# shellcheck source=/dev/null
. jails/base

zfs create tank/apps/"$JAIL_NAME"

cat <<-EOF >"$PKG_JSON"
{
	"pkgs": [
		"bash",
		"ca_root_nss",
		"python36",
		"py36-sqlite3",
		"py36-openssl"
	]
}
EOF

iocage create -r "$RELEASE" -n "$JAIL_NAME" -p "$PKG_JSON" \
	vnet="$VNET" \
	boot="$BOOT" \
	defaultrouter="$ROUTER" \
	bpf=yes \
	dhcp=on

iocage exec "$JAIL_NAME" env ASSUME_ALWAYS_YES=YES \
	python3.6 -Im ensurepip --upgrade --default-pip

cp "$ABS_DIR/sync" "/mnt/tank/iocage/jails/$JAIL_NAME/root/usr/local/bin"

rm -f "/mnt/tank/iocage/jails/$JAIL_NAME/root/bin/sync"

iocage exec "$JAIL_NAME" "pw groupadd -g $(getent group media | cut -d: -f3) -n media"
iocage exec "$JAIL_NAME" "pw user add media -c media -u $(id -u media) -d /nonexistent -s /usr/bin/nologin"
iocage exec "$JAIL_NAME" "pip install --upgrade pip gphotos-sync"
iocage exec "$JAIL_NAME" "mkdir -p /settings /mnt/media/photos && chown -R media:media /mnt/media/photos"

iocage fstab -a "$JAIL_NAME" "$SETTINGS_PATH" /settings nullfs rw 0 0

iocage fstab -a "$JAIL_NAME" "/mnt/tank/media/photos /mnt/media/photos nullfs rw 0 0"

