#!/usr/bin/env bash

# shellcheck source=/dev/null
. jails/base

set -x

JAIL_IP=192.168.1.70 && \
	export JAIL_IP

zfs create -o tank/apps/"$JAIL_NAME"

echo '{ "pkgs": ["mono"] }' > "$PKG_JSON"

iocage create -r "$RELEASE" -n "$JAIL_NAME" -p "$PKG_JSON" \
	vnet="$VNET" \
	boot="$BOOT" \
	defaultrouter="$ROUTER" \
	ip4_addr="$INTERFACE|$JAIL_IP/24"

iocage exec "$JAIL_NAME" "mkdir -p /settings /usr/local/etc/rc.d"
iocage fstab -a "$JAIL_NAME" "$SETTINGS_PATH" /settings nullfs rw 0 0

iocage exec "$JAIL_NAME" "ln -s /usr/local/bin/mono /usr/bin/mono"
iocage exec "$JAIL_NAME" "fetch $(github_release jackett jackett 20761502) -o /usr/local/share"
iocage exec "$JAIL_NAME" "tar -xzvf /usr/local/share/*.tar.gz -C /usr/local/share && rm /usr/local/share/*.tar.gz"

awk 'BEGIN { print "#!/bin/sh" } { print }' \
	< "$ABS_DIR/rc" \
	> "/mnt/tank/iocage/jails/$JAIL_NAME/root/usr/local/etc/rc.d/jackett"

cat <<-EOF | xargs -L1 iocage exec "$JAIL_NAME" > /dev/null 2>&1
	ln -s /usr/local/bin/mono /usr/bin/mono
	pw user add jackett -c jackett -d /nonexistent -s /usr/bin/nologin
	pw groupadd -g $(getent group media | cut -d: -f3) -n media
	pw user add media -c media -u $(id -u media) -d /nonexistent -s /usr/bin/nologin
	pw groupmod media -m jackett
	chown -R jackett:jackett /usr/local/share/Jackett /settings
	chmod u+x /usr/local/etc/rc.d/jackett
	sysrc jackett_enable=YES
	sysrc jackett_user=jackett
	sysrc jackett_group=jackett
	service jackett start
EOF
