#!/usr/bin/env bash

# shellcheck source=/dev/null
. jails/base

set -x

JAIL_IP=192.168.1.20 && \
	export JAIL_IP

zfs create -o recordsize=64K tank/apps/"$JAIL_NAME"

cat <<EOF >/tmp/pkglist.json
{
	"packagesite": "http://pkg.cdn.trueos.org/iocage/unstable",
	"pkgs": [
		"bash",
		"ca_root_nss",
		"devel/git",
		"ffmpeg",
		"go",
		"perl5",
		"plexmediaserver-plexpass",
		"wget"
	]
}
EOF

trap "rm /tmp/pkglist.json" EXIT

iocage create -r "$RELEASE" -n "$JAIL_NAME" -p /tmp/pkglist.json \
	vnet="$VNET" \
	boot="$BOOT" \
	defaultrouter="$ROUTER" \
	ip4_addr="$INTERFACE|$JAIL_IP/24"

iocage exec "$JAIL_NAME" "pw groupadd -g $(getent group media | cut -d: -f3) -n media"
iocage exec "$JAIL_NAME" "pw user add media -c media -u $(id -u media) -d /nonexistent -s /usr/bin/nologin"
iocage exec "$JAIL_NAME" "go get -u github.com/cloudflare/cloudflared/cmd/cloudflared"
iocage exec "$JAIL_NAME" "(crontab -l ; echo '@daily /usr/local/bin/plex_updater -vv -a') | sort - | uniq - | crontab -"
iocage exec "$JAIL_NAME" mkdir -p /settings /mnt/media/{movies,music,series}

iocage fstab -a "$JAIL_NAME" "$SETTINGS_PATH" /settings nullfs rw 0 0

# shellcheck disable=SC2016
find /mnt/tank/media/* -type d -maxdepth 0 -print0 \
	| xargs -0 -I@ bash -c "iocage fstab -a $JAIL_NAME @ /mnt/media/"'"$(basename @)"'" nullfs rw 0 0"

awk 'BEGIN { print "#!/bin/sh" } { print }' \
	< "$ABS_DIR/cloudflare/rc" \
	> "/mnt/tank/iocage/jails/$JAIL_NAME/root/usr/local/etc/rc.d/cloudflare"

cat <<-EOF | xargs -L1 iocage exec "$JAIL_NAME" > /dev/null 2>&1
	fetch -o /usr/local/bin/plex_updater https://git.io/Jeuy8
	chmod u+x /usr/local/bin/plex_updater
	pw useradd -n cloudflare -d -c wheel /nonexistent -s /usr/sbin/nologin
	mkdir /usr/local/cloudflare /settings/cloudflare
	cp /root/go/bin/cloudflared /usr/local/cloudflare/
	chown -R cloudflare /settings/cloudflare
	chmod u+x /usr/local/etc/rc.d/cloudflare
	sysrc cloudflare_user=cloudflare
	sysrc cloudflare_enable=YES
	chgrp -R media /mnt/media
	chown -R media:media /settings
	sysrc plexmediaserver_plexpass_user=media
	sysrc plexmediaserver_plexpass_group=media
	sysrc plexmediaserver_plexpass_support_path="/settings"
	sysrc plexmediaserver_plexpass_enable=YES
	service plexmediaserver_plexpass start
EOF

