#!/usr/bin/env bash

BASE_URL="plex.tv/api/downloads/5.json?channel=plexpass"
XML="$(sysrc -n plexmediaserver_plexpass_support_path)/Plex Media Server/Preferences.xml"
API="$BASE_URL&X-Plex-Token=$(xmllint --xpath "string(//Preferences/@PlexOnlineToken)" "$XML")"
PLEX="/usr/local/share/plexmediaserver-plexpass"

IFS='|' read -r VERSION URL SHA1 < <(wget -qO - "$API" | \
	jq -r '.computer.FreeBSD | [ .version, (.releases[0] | [.url, .checksum]) ] | flatten | join("|")')

CURRENTVER=$($PLEX/Plex_Media_Server --version)

to_int() {
	echo "$@" \
		| sed "s/^.*[^\.]\([0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\)\([^\.]\)/\1.0\2/" \
		| awk -F. '{ printf("%04d%04d%04d%04d%04d", $1, $2, $3, $4, $5) }'
}

if [ "$(to_int "$CURRENTVER")" -ge "$(to_int "$VERSION")" ]
then
	echo latest version already installed
	exit 0
fi

TEMP_FILE=$(mktemp /tmp/plex.XXXXXX) && \
	trap 'rm "$TEMP_FILE"' EXIT

if ! wget "$URL" -O "$TEMP_FILE"
then
	echo error downloading "$URL"
	exit 1
fi

if [ "$SHA1" != "$(sha1 -q "$TEMP_FILE")" ]
then
	echo checksum does not match
	exit 1
fi

TEMP_DIR=$(mktemp -d /tmp/XXXXXX) && \
	trap 'rm -rf "$TEMP_DIR"' EXIT

if ! tar -xjf "$TEMP_FILE" -C "$TEMP_DIR"
then
	echo something went wrong
	exit 1
fi

service plexmediaserver_plexpass stop

pushd "$PLEX" || exit
rm -rf -- * && cp -a "$TEMP_DIR/PlexMediaServer-$VERSION/." .
ln -s "lib/libpython2.7.so.1" "libpython2.7.so"
ln -s "Plex Media Server" "Plex_Media_Server"

service plexmediaserver_plexpass start

