#!/usr/bin/env bash

# shellcheck source=/dev/null
. jails/base

zfs create tank/apps/"$JAIL_NAME"

echo '{ "pkgs": [ "ca_root_nss" ] }' > "$PKG_JSON"

iocage create -r "$RELEASE" -n "$JAIL_NAME" -p "$PKG_JSON" \
	vnet="$VNET" \
	boot="$BOOT" \
	defaultrouter="$ROUTER" \
	bpf=yes \
	dhcp=on

iocage exec "$JAIL_NAME" mkdir -p /mnt/backup /usr/local/bin

cat <<-EOF >"/mnt/tank/iocage/jails/$JAIL_NAME/root/usr/local/bin/backup"
	#!/bin/sh

	pgrep -cx duplicacy || duplicacy backup -threads 1 -stats
EOF

iocage exec "$JAIL_NAME" "fetch $(github_release gilbertchen duplicacy) -o /usr/local/bin/duplicacy"
iocage exec "$JAIL_NAME" "(crontab -l; echo '@hourly /usr/local/bin/backup') | sort - | uniq - | crontab -"
iocage exec "$JAIL_NAME" "chmod u+x chmod /usr/local/bin/*"
