#!/usr/bin/env bash

# shellcheck source=/dev/null
. jails/base

zfs create -o tank/apps/"$JAIL_NAME"

echo '{ "pkgs": [ "bash" }' > "$PKG_JSON"

iocage create -r "$RELEASE" -n "$JAIL_NAME" -p "$PKG_JSON" \
	vnet="$VNET" \
	boot="$BOOT" \
	defaultrouter="$ROUTER" \
	bpf=yes \
	dhcp=on

iocage exec "$JAIL_NAME" mkdir -p /settings

iocage fstab -a "$JAIL_NAME" "$SETTINGS_PATH" /settings nullfs rw 0 0

iocage exec "$JAIL_NAME" "fetch $(github_release gilbertchen duplicacy) -o /usr/local/share"

cat <<-EOF | xargs -L1 iocage exec "$JAIL_NAME" > /dev/null 2>&1

EOF

