name: Shellcheck

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run shellcheck.
      run: |
        find . -type f -not -path '*/\.*' -exec grep -Eq '^#!(.*/|.*env +)(sh|bash|ksh)' {} \; -print |
          while IFS="" read -r file
          do
            shellcheck "$file"
          done
